# stage: 1
FROM node:12-alpine

# Install Docker CLI
RUN apk update && \
    apk add --no-cache docker openrc

WORKDIR /app
COPY . /app

RUN npm i --save --legacy-peer-deps

RUN npm install -g nodemon
RUN npm install -g ts-node

CMD [ "npm", "run", "dev" ]